AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SNSTopicARN:
    Type: String
Resources:
  ${AlarmId}:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "Alarm that raised when something happened"
      AlarmName: ${AlarmName}
      AlarmActions:
        - !Ref SNSTopicARN
      MetricName: MessagesCount
      Namespace: AWS/SNS
      Statistic: Sum
      Dimensions:
        - Name: TopicName
          Value: ${SnsTopic}
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: ${Threshold}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Unit: Count
